# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrlShort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shortUrl',
            field=models.SlugField(max_length=6, null=True),
        ),
    ]
